version: '3'
services:
    dj-server:
        build:
            context: .
            dockerfile: Dockerfile
        image: dj-service
        container_name: dj-service
        ports:
            - 8089:3002
    dj-redis:
        image: redis
        container_name: dj-redis
        ports:
            - 6378:6379
        environment:
            - TZ=Asia/Shanghai
    dj-mongo:
        image: mongo
        container_name: dj-mongo
        restart: always
        volumes:
            - '.docker-volumes/mongo/data:/data/db'
        environment:
            - MONGO_INITDB_DATABASE=djtest_mongo
            - TZ=Asia/Shanghai
        ports:
            - '27015:27017'
    dj-mysql:
        image: mysql
        container_name: dj-mysql
        restart: always
        privileged: true
        command: --default-authentication-plugin=mysql_native_password # 远程访问
        ports:
            - 3305:3306
        volumes:
            - .docker-volumes/mysql/log:/var/log/mysql # 日志
            - .docker-volumes/mysql/data:/var/lib/mysql # db
            - .docker-volumes/mysql/init:/docker-entrypoint-initdb.d/ # 初始化 sql
        environment:
            - MYSQL_DATABASE=djtest_mysql
            - MYSQL_ROOT_PASSWORD=dingjia3113
            - TZ=Asia/Shanghai
